# Generated by Django 3.2.8 on 2021-10-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211028_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], max_length=20),
        ),
    ]
