# Generated by Django 3.2.8 on 2021-10-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table=None,
        ),
    ]
