# Generated by Django 3.2.8 on 2021-10-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bg_image_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bg_image_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
