# Generated by Django 3.2.8 on 2021-10-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211031_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bg_image_url',
            field=models.CharField(blank=True, help_text='Zorunlu değil, Eğer resim kaybolursa arkaplan fotoğrafı olarak bu url adresindeki fotoğraf kalır', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bg_image_url',
            field=models.CharField(blank=True, help_text='Zorunlu değil, Eğer resim kaybolursa arkaplan fotoğrafı olarak bu url adresindeki fotoğraf kalır', max_length=254, null=True),
        ),
    ]
